apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: prowlarr
    environment: prod
  name: prod-prowlarr
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prowlarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: prowlarr
    spec:
      containers:
      - env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              key: PUID
              name: servarr-config
        - name: PGID
          valueFrom:
            configMapKeyRef:
              key: PGID
              name: servarr-config
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: servarr-config
        - name: PROWLARR__APP__INSTANCENAME
          value: "prowlarr"
        - name: PROWLARR__APP__THEME
          value: "dark"
        - name: PROWLARR__AUTH__APIKEY
          value: <path:secret/data/apps/sevarr/prowlarr/prod#api_key>
        - name: PROWLARR__AUTH__ENABLED
          value: "true"
        - name: PROWLARR__AUTH__METHOD
          value: "External"
        - name: PROWLARR__AUTH__REQUIRED
          value: "true"
        - name: PROWLARR__LOG__ANALYTICSENABLED
          value: "false"
        - name: PROWLARR__POSTGRES__USER
          value: <path:secret/data/apps/sevarr/prowlarr/prod#db_user>
        - name: PROWLARR__POSTGRES__PASSWORD
          value: <path:secret/data/apps/sevarr/prowlarr/prod#db_password>
        - name: PROWLARR__SERVER__BINDADDRESS
          value: "*"
        - name: PROWLARR__SERVER__PORT
          value: "7878"
        - name: PROWLARR__UPDATE__MECHANISM
          value: "Docker"
        - name: PROWLARR__SERVER__PROXYENABLE
          value: "true"
        - name: PROWLARR__SERVER__ENABLESSL
          value: "false"
        image: lscr.io/linuxserver/prowlarr:latest
        name: prowlarr
        ports:
        - containerPort: 9696
          name: http
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 50m
            memory: 128Mi
        volumeMounts:
        - mountPath: /config
          name: config
        imagePullPolicy: IfNotPresent
      securityContext:
        fsGroup: 3000
        runAsGroup: 3000
        runAsUser: 3000
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prod-prowlarr-config
