apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: radarr
    environment: prod
  name: prod-radarr
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: radarr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: radarr
    spec:
      containers:
      - env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              key: PUID
              name: servarr-config
        - name: PGID
          valueFrom:
            configMapKeyRef:
              key: PGID
              name: servarr-config
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: servarr-config
        - name: RADARR__APP__INSTANCENAME
          value: "radarr"
        - name: RADARR__APP__THEME
          value: "dark"
        - name: RADARR__AUTH__APIKEY
          value: <path:secrets/data/apps/servarr/radarr/prod#api_key>
        - name: RADARR__AUTH__ENABLED
          value: "true"
        - name: RADARR__AUTH__METHOD
          value: "External"
        - name: RADARR__AUTH__REQUIRED
          value: "true"
        - name: RADARR__LOG__ANALYTICSENABLED
          value: "false"
        - name: RADARR__POSTGRES__USER
          value: <path:secrets/data/apps/servarr/radarr/prod#db_user>
        - name: RADARR__POSTGRES__PASSWORD
          value: <path:secrets/data/apps/servarr/radarr/prod#db_password>
        - name: RADARR__SERVER__BINDADDRESS
          value: "*"
        - name: RADARR__SERVER__PORT
          value: "7878"
        - name: RADARR__UPDATE__MECHANISM
          value: "Docker"
        - name: RADARR__SERVER__PROXYENABLE
          value: "true"
        - name: RADARR__SERVER__ENABLESSL
          value: "false"
        - name: SSL_CERT_FILE
          value: /etc/ssl/custom/ca-bundle.crt
        image: lscr.io/linuxserver/radarr:latest
        name: radarr
        ports:
        - containerPort: 7878
          name: http
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - mountPath: /config
          name: config
        - mountPath: /data/media/movies
          name: movies
        - mountPath: /downloads
          name: downloads
        - mountPath: /etc/ssl/custom
          name: ca-certs
          readOnly: true
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/arch: amd64
      securityContext:
        fsGroup: 3000
        runAsGroup: 3000
        runAsUser: 3000
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prod-radarr-config
      - name: movies
        persistentVolumeClaim:
          claimName: prod-media-movies
      - name: downloads
        persistentVolumeClaim:
          claimName: prod-downloads
      - name: ca-certs
        configMap:
          name: internal-ca-bundle
