apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: lidarr-ingress
  namespace: servarr
  annotations:
#    cert-manager.io/issuer: "vault-issuer" # Commented out so it uses the certificate's issuerRef
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
    nginx.ingress.kubernetes.io/proxy-request-buffering: "off"
    avp.kubernetes.io/path: "secret/data/apps/servarr/lidarr/prod"
spec:
  ingressClassName: nginx 
  tls:
  - hosts:
    - <lidarr_url>
    secretName: servarr-tls-secret
  rules:
  - host: <lidarr_url>
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: prod-lidarr
            port:
              number: 9696
