apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: jellyseerr
    environment: prod
  name: prod-jellyseerr
  namespace: servarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jellyseerr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jellyseerr
    spec:
      containers:
      - env:
        - name: PUID
          valueFrom:
            configMapKeyRef:
              key: PUID
              name: servarr-config
        - name: PGID
          valueFrom:
            configMapKeyRef:
              key: PGID
              name: servarr-config
        - name: TZ
          valueFrom:
            configMapKeyRef:
              key: TZ
              name: servarr-config
        - name: API_KEY
          value: <path:secret/data/apps/servarr/jellyseerr/prod#api_key>
        - name: DB_USER
          value: <path:secret/data/apps/servarr/jellyseerr/prod#db_user>
        - name: DB_PASS
          value: <path:secret/data/apps/servarr/jellyseerr/prod#db_password>
        - name: NODE_EXTRA_CA_CERTS
          value: /etc/ssl/custom/ca-bundle.crt
        image: ghcr.io/seerr-team/seerr:2.7.3
        name: jellyseerr
        ports:
        - containerPort: 5055
          name: http
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
          requests:
            cpu: 100m
            memory: 128Mi
        volumeMounts:
        - mountPath: /app/config
          name: config
        - mountPath: /etc/ssl/custom
          name: ca-certs
          readOnly: true
        imagePullPolicy: IfNotPresent
      nodeSelector:
        kubernetes.io/arch: amd64
      securityContext:
        fsGroup: 3000
        runAsGroup: 3000
        runAsUser: 3000
      volumes:
      - name: config
        persistentVolumeClaim:
          claimName: prod-jellyseerr-config
      - name: ca-certs
        configMap:
          name: internal-ca-bundle
